spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
          auto-add-partitions: true
      bindings:
        output:
          destination: kafka.newspipeline.producer.news
          content-type: application/*+avro
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 2
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    preferIpAddress: true

server:
  port: 9084